;;; Douglas P. Fields, Jr. - symbolics@lisp.engineer
;;;
;;; Developed with Antigravity CLI (Gemini 3.5 Flash and 3.1 Pro)
;;;
;;; C# Assembly Lisp Package Generator
;;;
;;; This module parses metadata generated by AssemblyToLispy and produces
;;; Common Lisp source files mapping C# classes to Lisp packages.

(in-package :assembly-package-generator)

(defparameter *generator-version* 17
  "Integer version number for the generated Lisp source files.
   Version history:
   1 - Initial generator mapping C# classes to Lisp packages.
   2 - Added symbol-macro support for C# static properties/fields and Lisp symbol shadowing.
   3 - Refined constant property determination.
   4 - Added operator overloading name mapping (e.g. mapping op_Multiply to *).
   5 - Added CLOS class registration support and mapped C# inequality operator to not=.
   6 - Added support for treating selected read-only static properties as constants via configuration.
   7 - Eliminated duplicate exports and shadows in generated package files.
   8 - Mapped implicit and explicit conversion operators and filtered exports to exclude undefined members.
   9 - Added instance property accessors and mutators.
   10 - Added method overload handling with classification into clean vs dirty overloads,
        type-suffixed naming for multi-overload methods, passthrough &rest functions,
        typed-call optimization for value type receivers, and dirty overload documentation.
   11 - Added support for C# constructors (new) with overload dispatch and struct parameterless constructor injection.
   12 - Added support for C# generic methods of exactly one type argument using dotnet:invoke-generic and dotnet:static-generic.
   13 - Refactored C# overloaded operator passthrough generation to dispatch based on argument types and counts in Lisp, avoiding MissingMethodExceptions.
   14 - Qualified standard Common Lisp comparison function cl:= in emitted passthrough code, preventing it from resolving to the shadowed = operator of the generated package.
   15 - Protected critical Lisp syntax symbols (quote, function, t, nil) from being shadowed by mapping conflicting C# member names to quote!, function!, t!, nil!; qualified other standard Common Lisp symbols in generated templates with cl: prefix.
   16 - Tracked is-static-overload-p per clean method overload inside Case 3 (instead of using group-wide static-p) to ensure overloaded static methods are correctly generated as static wrappers.
   17 - Mapped C# field/property 'NaN' to Lisp 'nan' in camel-to-kebab; mapped 'IsSomething' methods/properties to 'something?' in map-member-name.")

(defun camel-to-kebab (name)
  "Convert a PascalCase/camelCase string to Lisp kebab-case.
   Also maps dot characters '.' to hyphens '-'."
  (if (string= name "NaN")
      "nan"
      (let ((len (length name)))
        (with-output-to-string (sb)
          (loop for i from 0 to (1- len)
                for c = (char name i)
                do (cond
                     ((char= c #\.)
                      (write-char #\- sb))
                     ((upper-case-p c)
                      (when (and (> i 0)
                                 (char/= (char name (1- i)) #\-)
                                 (char/= (char name (1- i)) #\.)
                                 (or (not (upper-case-p (char name (1- i))))
                                     (and (< (1+ i) len)
                                          (lower-case-p (char name (1+ i))))))
                        (write-char #\- sb))
                      (write-char (char-downcase c) sb))
                     (t
                      (write-char c sb))))))))

(defun split-string (string &optional (separator #\;))
  "Split a string into a list of substrings at occurrences of the separator character."
  (let ((result nil)
        (start 0)
        (len (length string)))
    (loop for i from 0 to (1- len)
          do (when (char= (char string i) separator)
               (push (subseq string start i) result)
               (setf start (1+ i))))
    (when (<= start len)
      (push (subseq string start len) result))
    (nreverse result)))

(defun map-param-name (name)
  "Convert a C# parameter name to a safe Lisp parameter name,
   renaming reserved words where necessary."
  (let ((kebab (camel-to-kebab name)))
    (cond
      ((string= kebab "t") "t-val")
      ((string= kebab "nil") "nil-val")
      (t kebab))))

(defun map-member-name (name)
  "Convert a Pascal/camel C# member name to a kebab-case Lisp name,
   renaming critical Common Lisp symbols to avoid shadowing them,
   converting IsSomething to something?, and handling NaN."
  (let* ((kebab (cond
                  ((and (uiop:string-prefix-p "Is" name)
                        (> (length name) 2)
                        (upper-case-p (char name 2)))
                   (format nil "~A?" (camel-to-kebab (subseq name 2))))
                  (t (camel-to-kebab name)))))
    (cond
      ((string= kebab "quote") "quote!")
      ((string= kebab "function") "function!")
      ((string= kebab "t") "t!")
      ((string= kebab "nil") "nil!")
      (t kebab))))

(defun escape-lisp-string (str)
  "Escapes double quotes and backslashes in a string for safe output within Lisp strings."
  (with-output-to-string (out)
    (loop for c across str
          do (cond
               ((char= c #\") (write-string "\\\"" out))
               ((char= c #\\) (write-string "\\\\" out))
               (t (write-char c out))))))

(defun get-iso-8601-time ()
  "Get the current UTC time formatted as an ISO 8601 string."
  (multiple-value-bind (second minute hour date month year day-of-week daylight-saving-p time-zone)
      (decode-universal-time (get-universal-time) 0)
    (declare (ignore day-of-week daylight-saving-p time-zone))
    (format nil "~4,'0D-~2,'0D-~2,'0DT~2,'0D:~2,'0D:~2,'0DZ"
            year month date hour minute second)))

(defun literal-field-p (field)
  "Checks if a field plist defines a static literal/constant field."
  (and (getf field :static)
       (getf field :literal)))

(defun runtime-readonly-field-p (field)
  "Checks if a field plist defines a static init-only field that is not literal."
  (and (getf field :static)
       (getf field :init-only)
       (not (getf field :literal))))

(defun constant-property-p (prop)
  "Checks if a property plist defines a static read-only property."
  (and (getf prop :static)
       (getf prop :readable)
       (not (getf prop :writeable))))

(defun instance-property-p (prop)
  "Checks if a property plist defines an instance property."
  (not (getf prop :static)))

(defun static-method-p (method)
  "Checks if a method plist defines a static method."
  (getf method :is-static))

(defun public-instance-field-p (field)
  "Checks if a field plist defines a public instance field."
  (and (not (getf field :static))
       (getf field :public)))


(defun generic-type-p (type-str)
  "Checks if a C# type signature string represents a generic type (contains a backtick or exclamation point)."
  (and type-str (or (find #\` type-str) (find #\! type-str))))

(defun simple-method-p (method all-methods)
  "Returns t if the method qualifies for Phase 1 compilation.
   Criteria:
   - No overloads (exactly one method signature with this name in the class).
   - No generic parameters/return type (or exactly one generic type argument).
   - No default parameter values.
   - No special parameter modifiers (ref, out, ref-readonly, params).
   - No operator overloads.
   - No property accessors (get_/set_)."
  (let* ((name (getf method :name))
         (params (getf method :parameters))
         (static-p (getf method :is-static))
         (is-generic (getf method :is-generic))
         (arity (getf method :generic-arity)))
    (declare (ignore static-p))
    (and name
         ;; Exclude operators and property accessors
         (not (uiop:string-prefix-p "op_" name))
         (not (uiop:string-prefix-p "get_" name))
         (not (uiop:string-prefix-p "set_" name))
         ;; Check for no overloads in the class
         (= 1 (count name all-methods :key (lambda (m) (getf m :name)) :test #'string=))
         ;; Only support generic methods if they have exactly one type argument
         (or (not is-generic) (eql arity 1))
         ;; Check return type for generic markers
         (not (generic-type-p (getf method :return-type)))
         ;; Check all parameters
         (every (lambda (p)
                  (and (not (getf p :has-default))
                       (not (getf p :out))
                       (not (getf p :ref))
                       (not (getf p :ref-readonly))
                       (not (getf p :params))
                       (not (generic-type-p (getf p :type)))))
                 params))))

(defun clean-method-p (method)
  "Returns t if the method is 'clean' (no ref/out/params/defaults/generics).
   Unlike simple-method-p, this does NOT check for uniqueness of the method name,
   allowing it to be used for overloaded methods."
  (let* ((name (getf method :name))
         (params (getf method :parameters))
         (is-generic (getf method :is-generic))
         (arity (getf method :generic-arity)))
    (and name
         (not (uiop:string-prefix-p "op_" name))
         (not (uiop:string-prefix-p "get_" name))
         (not (uiop:string-prefix-p "set_" name))
         ;; Only support generic methods if they have exactly one type argument
         (or (not is-generic) (eql arity 1))
         (not (generic-type-p (getf method :return-type)))
         (every (lambda (p)
                  (and (not (getf p :has-default))
                       (not (getf p :out))
                       (not (getf p :ref))
                       (not (getf p :ref-readonly))
                       (not (getf p :params))
                       (not (generic-type-p (getf p :type)))))
                params))))

(defun dirty-method-p (method)
  "Returns t if the method has any special parameter modifiers (ref, out, params, or defaults).
   Complement to clean-method-p; a method may be neither clean nor dirty
   if it is an operator or accessor."
  (let ((params (getf method :parameters)))
    (some (lambda (p)
            (or (getf p :has-default)
                (getf p :out)
                (getf p :ref)
                (getf p :ref-readonly)
                (getf p :params)))
          params)))

(defun simple-type-name (full-type-name)
  "Extract the simple (unqualified) type name from a fully qualified C# type name.
   e.g., \"Microsoft.Xna.Framework.Vector2\" => \"Vector2\"
         \"System.Single\" => \"Single\"
         \"System.Collections.Generic.List`1\" => \"List\""
  (let* ((dot-pos (or (position #\. full-type-name :from-end t) -1))
         (base-name (subseq full-type-name (1+ dot-pos)))
         (backtick-pos (position #\` base-name)))
    (if backtick-pos
        (subseq base-name 0 backtick-pos)
        base-name)))

(defun method-overload-name (method)
  "Generate a disambiguated Lisp function name for an overloaded method,
   by appending kebab-cased simple parameter type names.
   e.g., Contains(Vector2) => \"contains-vector-2\"
         DistanceSquared(Vector2, Vector2) => \"distance-squared-vector-2-vector-2\""
  (let* ((base-name (map-member-name (getf method :name)))
         (params (getf method :parameters))
         (type-suffixes (mapcar (lambda (p)
                                  (camel-to-kebab (simple-type-name (getf p :type))))
                                params)))
    (if type-suffixes
        (format nil "~A-~{~A~^-~}" base-name type-suffixes)
        base-name)))

(defun method-signature-str (method)
  "Return a human-readable signature string for a method, e.g.
   'Contains(ref Rectangle, out bool) -> void'."
  (let* ((name (getf method :name))
         (return-type (simple-type-name (or (getf method :return-type) "void")))
         (params (getf method :parameters))
         (param-strs (mapcar (lambda (p)
                               (let ((modifier-str (cond
                                                     ((getf p :ref) "ref ")
                                                     ((getf p :out) "out ")
                                                     ((getf p :params) "params ")
                                                     (t "")))
                                     (type-str (simple-type-name (getf p :type))))
                                 (format nil "~A~A" modifier-str type-str)))
                             params)))
    (format nil "~A(~{~A~^, ~}) -> ~A" name param-strs return-type)))

(defun clean-constructor-p (ctor)
  "Returns t if the constructor is 'clean' (no ref/out/params/defaults/generics)."
  (let ((params (getf ctor :parameters)))
    (every (lambda (p)
             (and (not (getf p :has-default))
                  (not (getf p :out))
                  (not (getf p :ref))
                  (not (getf p :ref-readonly))
                  (not (getf p :params))
                  (not (generic-type-p (getf p :type)))))
           params)))

(defun dirty-constructor-p (ctor)
  "Returns t if the constructor has any special parameter modifiers (ref, out, params, or defaults)."
  (let ((params (getf ctor :parameters)))
    (some (lambda (p)
            (or (getf p :has-default)
                (getf p :out)
                (getf p :ref)
                (getf p :ref-readonly)
                (getf p :params)))
          params)))

(defun constructor-overload-name (ctor)
  "Generate a disambiguated Lisp function name for an overloaded constructor,
   by appending kebab-cased simple parameter type names.
   e.g., ctor(float, float) => \"new-single-single\""
  (let* ((params (getf ctor :parameters))
         (type-suffixes (mapcar (lambda (p)
                                  (camel-to-kebab (simple-type-name (getf p :type))))
                                params)))
    (if type-suffixes
        (format nil "new-~{~A~^-~}" type-suffixes)
        "new")))

(defun constructor-signature-str (ctor)
  "Return a human-readable signature string for a constructor, e.g.
   'new(ref Rectangle, out bool)'."
  (let* ((params (getf ctor :parameters))
         (param-strs (mapcar (lambda (p)
                               (let ((modifier-str (cond
                                                     ((getf p :ref) "ref ")
                                                     ((getf p :out) "out ")
                                                     ((getf p :params) "params ")
                                                     (t "")))
                                     (type-str (simple-type-name (getf p :type))))
                                 (format nil "~A~A" modifier-str type-str)))
                             params)))
    (format nil "new(~{~A~^, ~})" param-strs)))

(defun build-docstring (summary returns parameters doc-plist)
  "Builds a formatted docstring from documentation elements."
  (with-output-to-string (out)
    (when (and summary (> (length summary) 0))
      (format out "Summary: ~A~%" summary))
    (when (and returns (> (length returns) 0))
      (format out "Returns: ~A~%" returns))
    (when (and parameters doc-plist)
      (let ((doc-params (getf doc-plist :parameters)))
        (format out "Parameters:~%")
        (dolist (p parameters)
          (let* ((pname (getf p :name))
                 (ptype (getf p :type))
                 (pdoc (find pname doc-params :key (lambda (dp) (getf dp :name)) :test #'string=))
                 (pdesc (if pdoc (getf pdoc :description) "")))
            (format out "  - ~A (~A): ~A~%"
                    (map-param-name pname)
                    ptype
                    pdesc)))))))

(defun format-param-type-check (param-type arg-str)
  "Returns a Lisp type checking expression string for the given C# parameter type."
  (cond
    ((member param-type '("System.Double" "System.Single" "System.Int32" "System.Int64" "System.Int16" "System.Byte" "System.Decimal") :test #'string=)
     (format nil "(cl:numberp ~A)" arg-str))
    ((string= param-type "System.Boolean")
     (format nil "(cl:typep ~A 'cl:boolean)" arg-str))
    ((string= param-type "System.String")
     (format nil "(cl:stringp ~A)" arg-str))
    (t
     (format nil "(monoutils:dotnet-p ~A)" arg-str))))

(defun format-overload-test (cm)
  "Generates a Lisp conditional test expression string for checking if the runtime arguments match the method's parameters."
  (let* ((params (getf cm :parameters))
         (arg-count (length params)))
    (if (= arg-count 0)
        (format nil "(cl:= (cl:length args) 0)")
        (let ((checks (loop for p in params
                            for idx from 0
                            collect (format-param-type-check (getf p :type) (format nil "(cl:nth ~D args)" idx)))))
          (format nil "(cl:and (cl:= (cl:length args) ~D)~{ ~A~})" arg-count checks)))))

(defun generate-class-file (class-plist output-dir &optional constant-properties-list)
  "Generates the Lisp source file for a single class plist."
  (let* ((fq-name (getf class-plist :fully-qualified-name))
         (pkg-name (camel-to-kebab fq-name))
         (output-file (merge-pathnames (make-pathname :name pkg-name :type "lisp")
                                       (pathname (concatenate 'string output-dir "/"))))
         (fields (getf class-plist :fields))
         (properties (getf class-plist :properties))
         (methods (getf class-plist :methods))
         (kind (getf class-plist :kind))
         (raw-ctors (getf class-plist :constructors))
         ;; Structs (value types) in C# have an implicit parameterless constructor.
         ;; If no parameterless constructor is in raw-ctors, we inject one.
         (ctors (if (and (eq kind :struct)
                         (not (some (lambda (ctor) (null (getf ctor :parameters))) raw-ctors)))
                    (cons '(:parameters nil :public t) raw-ctors)
                    raw-ctors))
         (is-value-type-p (or (eq kind :struct) (eq kind :enum)))
         (creation-time (get-iso-8601-time)))
    
    (ensure-directories-exist output-file :verbose t)
    
    ;; 1. Analyze and extract valid Phase 1 members
    (let* ((literal-fields (remove-if-not #'literal-field-p fields))
           (runtime-fields-all (remove-if-not #'runtime-readonly-field-p fields))
           (pure-const-fields (remove-if-not (lambda (f) (or (member "*" constant-properties-list :test #'string=) (member (getf f :name) constant-properties-list :test #'string-equal))) runtime-fields-all))
           (dynamic-const-fields (remove-if (lambda (f) (or (member "*" constant-properties-list :test #'string=) (member (getf f :name) constant-properties-list :test #'string-equal))) runtime-fields-all))
           (const-props (remove-if-not #'constant-property-p properties))
           (pure-const-props (remove-if-not (lambda (p) (or (member "*" constant-properties-list :test #'string=) (member (getf p :name) constant-properties-list :test #'string-equal))) const-props))
           (dynamic-const-props (remove-if (lambda (p) (or (member "*" constant-properties-list :test #'string=) (member (getf p :name) constant-properties-list :test #'string-equal))) const-props))
           (instance-props (remove-if-not #'instance-property-p properties))
           ;; Group methods by name for overload-aware generation
           (non-operator-non-accessor-methods
             (remove-if (lambda (m)
                          (or (uiop:string-prefix-p "op_" (getf m :name))
                              (uiop:string-prefix-p "get_" (getf m :name))
                              (uiop:string-prefix-p "set_" (getf m :name))
                              (generic-type-p (getf m :return-type))
                              (some (lambda (p) (generic-type-p (getf p :type)))
                                    (getf m :parameters))))
                        methods))
           (method-groups
             (let ((table (make-hash-table :test #'equal)))
               (dolist (m non-operator-non-accessor-methods)
                 (push m (gethash (getf m :name) table)))
               (let ((groups nil))
                 (maphash (lambda (name methods)
                            (push (cons name (nreverse methods)) groups))
                           table)
                 (nreverse groups))))
           (clean-ctors (remove-if-not #'clean-constructor-p ctors))
           (dirty-ctors (remove-if-not #'dirty-constructor-p ctors))
           (clean-ctor-count (length clean-ctors))
           (dirty-ctor-count (length dirty-ctors))
           (exports nil)
           (shadows nil))
      
      ;; Collect all exports
      (push "<type>" exports)
      (push "<type-str>" exports)
      (push "<creation>" exports)
      (push "<version>" exports)
      
      ;; Collect constructor exports
      (when (> clean-ctor-count 0)
        (push "new" exports)
        (when (>= clean-ctor-count 2)
          (dolist (c clean-ctors)
            (let ((params (getf c :parameters)))
              (when params
                (push (constructor-overload-name c) exports))))))
      
      (dolist (f literal-fields)
        (push (format nil "+~A+" (camel-to-kebab (getf f :name))) exports))
      (dolist (f pure-const-fields)
        (push (format nil "+~A+" (camel-to-kebab (getf f :name))) exports))
      (dolist (f dynamic-const-fields)
        (push (map-member-name (getf f :name)) exports))
      (dolist (p pure-const-props)
        (push (format nil "+~A+" (camel-to-kebab (getf p :name))) exports))
      (dolist (p dynamic-const-props)
        (push (map-member-name (getf p :name)) exports))
      (dolist (p instance-props)
        (let* ((pname (map-member-name (getf p :name)))
               (readable (getf p :readable)))
          (if readable
              (push pname exports)
              (push (format nil "set-~A" pname) exports))))
      ;; Collect method exports from method groups
      (dolist (group method-groups)
        (let* ((name (car group))
               (clean-methods (remove-if-not #'clean-method-p (cdr group)))
               (clean-count (length clean-methods)))
          (when (> clean-count 0)
            (push (map-member-name name) exports))
          (when (>= clean-count 2)
            ;; Export type-suffixed names for multi-overload methods
            (dolist (cm clean-methods)
              (push (method-overload-name cm) exports)))))
      
      ;; Remove duplicates from exports while preserving order
      (setf exports (remove-duplicates (nreverse exports) :test #'string= :from-end t))
      
      ;; Identify exported symbols that conflict with CL and must be shadowed
      (dolist (exp exports)
        (multiple-value-bind (sym status) (find-symbol (string-upcase exp) :common-lisp)
          (when (and sym (eq status :external))
            (push exp shadows))))
      ;; Remove duplicates from shadows while preserving order
      (setf shadows (remove-duplicates (nreverse shadows) :test #'string= :from-end t))
      
      ;; 2. Write to the Lisp output file
      (with-open-file (stream output-file :direction :output :if-exists :supersede :if-does-not-exist :create)
        ;; Comments
        (format stream ";;; Generated automatically. Do not edit.~%")
        (format stream ";;; Class: ~A~%" fq-name)
        (format stream ";;; Generator Version: ~D~%" *generator-version*)
        (format stream ";;; Creation Date: ~A~%~%" creation-time)
        
        ;; Preamble
        (format stream "(cl:in-package :cl-user)~%~%")
        (format stream "(cl:defpackage :~A~%" pkg-name)
        (format stream "  (:use :cl)~%")
        (when shadows
          (format stream "  (:shadow~%")
          (dolist (shad shadows)
            (format stream "   #:~A~%" shad))
          (format stream "  )~%"))
        (format stream "  (:export~%")
        (dolist (exp exports)
          (format stream "   #:~A~%" exp))
        (format stream "  ))~%~%")
        
        (format stream "(cl:in-package :~A)~%~%" pkg-name)
        
        ;; Type Constants
        (format stream "(cl:defconstant <type> (monoutils:get-type \"~A\"))~%" fq-name)
        (format stream "(cl:defconstant <type-str> \"~A\")~%" fq-name)
        (format stream "(cl:defconstant <creation> \"~A\")~%" creation-time)
        (format stream "(cl:defconstant <version> ~D)~%~%" *generator-version*)
        
        ;; CLOS Type Registration
        (format stream ";; Register C# Type with CLOS~%")
        (format stream "(cl:eval-when (:compile-toplevel :load-toplevel :execute)~%")
        (format stream "  (dotnet:static \"DotCL.Runtime\" \"EnsureDotNetTypeClass\"~%")
        (format stream "                 (dotnet:resolve-type \"~A\")))~%~%" fq-name)
        
        ;; Constructors
        (cond
          ;; Case 1: No clean constructors - all are dirty
          ((and (> dirty-ctor-count 0) (= clean-ctor-count 0))
           (format stream ";; The following C# ~A constructors have special parameter types~%" fq-name)
           (format stream ";; (ref, out, params, or defaults) and are not yet supported:~%")
           (dolist (dc dirty-ctors)
             (format stream ";;   ~A~%" (constructor-signature-str dc)))
           (format stream "~%"))
          
          ;; Case 2: Single clean constructor
          ((= clean-ctor-count 1)
           (let* ((c (first clean-ctors))
                  (c-doc (getf c :documentation))
                  (summary (getf c-doc :summary))
                  (returns (getf c-doc :returns))
                  (params (getf c :parameters))
                  (param-names (mapcar (lambda (p) (map-param-name (getf p :name))) params))
                  (args-str (format nil "~{~A~^ ~}" param-names))
                  (docstring (build-docstring summary returns params c-doc))
                  (escaped-docstring (escape-lisp-string docstring)))
             (format stream "(cl:defun new (~A)~%" args-str)
             (when (> (length escaped-docstring) 0)
               (format stream "  \"~A\"~%" escaped-docstring))
             (format stream "  (dotnet:new <type-str>~@[ ~{~A~^ ~}~]))~%~%" param-names)
             ;; Emit dirty constructor doc-comments if any
             (when (> dirty-ctor-count 0)
               (format stream ";; Note: ~A also has the following constructors with special~%" fq-name)
               (format stream ";; parameter types (ref, out, params, or defaults) that are not~%")
               (format stream ";; yet supported:~%")
               (dolist (dc dirty-ctors)
                 (format stream ";;   ~A~%" (constructor-signature-str dc)))
               (format stream "~%"))))
          
          ;; Case 3: Multiple clean constructors
          ((>= clean-ctor-count 2)
           ;; Generate passthrough &rest function for DotCL runtime dispatch
           (format stream "(cl:defun new (cl:&rest args)~%")
           (format stream "  \"Passthrough constructor for ~A. Dispatches at runtime.\"~%" fq-name)
           (format stream "  (cl:apply (cl:function dotnet:new) <type-str> args))~%~%")
           ;; Generate per-overload typed functions with type-suffixed names
           (dolist (c clean-ctors)
             (let ((params (getf c :parameters)))
               (when params
                 (let* ((cname (constructor-overload-name c))
                        (c-doc (getf c :documentation))
                        (summary (getf c-doc :summary))
                        (returns (getf c-doc :returns))
                        (param-names (mapcar (lambda (p) (map-param-name (getf p :name))) params))
                        (overload-signature (constructor-signature-str c))
                        (args-str (format nil "~{~A~^ ~}" param-names))
                        (docstring (build-docstring summary returns params c-doc))
                        (overload-note (format nil "Calls ~A constructor ~A" fq-name overload-signature))
                        (full-docstring (if (> (length docstring) 0)
                                            (concatenate 'string overload-note ". " docstring)
                                            overload-note))
                        (escaped-full-doc (escape-lisp-string full-docstring)))
                   (format stream "(cl:defun ~A (~A)~%" cname args-str)
                   (format stream "  \"~A\"~%" escaped-full-doc)
                   (format stream "  (dotnet:new <type-str>~@[ ~{~A~^ ~}~]))~%~%" param-names)))))
           ;; Emit dirty constructor doc-comments if any
           (when (> dirty-ctor-count 0)
             (format stream ";; Note: ~A also has the following constructors with special~%" fq-name)
             (format stream ";; parameter types (ref, out, params, or defaults) that are not~%")
             (format stream ";; yet supported:~%")
             (dolist (dc dirty-ctors)
               (format stream ";;   ~A~%" (constructor-signature-str dc)))
             (format stream "~%"))))
        
        ;; Compile-Time Constants (Literal Fields)
        (dolist (f literal-fields)
          (let* ((cname (format nil "+~A+" (camel-to-kebab (getf f :name))))
                 (f-doc (getf (getf f :documentation) :summary))
                 (doc-str (if f-doc (escape-lisp-string f-doc) "")))
            (format stream "(cl:defconstant ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf f :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))
        
        ;; Runtime Read-Only Fields (Constants)
        (dolist (f pure-const-fields)
          (let* ((cname (format nil "+~A+" (camel-to-kebab (getf f :name))))
                 (f-doc (getf (getf f :documentation) :summary))
                 (doc-str (if f-doc (escape-lisp-string f-doc) "")))
            (format stream "(cl:defconstant ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf f :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))

        ;; Runtime Read-Only Fields (Dynamic)
        (dolist (f dynamic-const-fields)
          (let* ((cname (map-member-name (getf f :name)))
                 (f-doc (getf (getf f :documentation) :summary))
                 (doc-str (if f-doc (escape-lisp-string f-doc) "")))
            (format stream "(cl:define-symbol-macro ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf f :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))
        
        ;; Runtime Read-Only Properties
        ;; Pure Constant Properties
        (dolist (p pure-const-props)
          (let* ((cname (format nil "+~A+" (camel-to-kebab (getf p :name))))
                 (p-doc (getf (getf p :documentation) :summary))
                 (doc-str (if p-doc (escape-lisp-string p-doc) "")))
            (format stream "(cl:defconstant ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf p :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))

        ;; Runtime Read-Only Properties
        (dolist (p dynamic-const-props)
          (let* ((cname (map-member-name (getf p :name)))
                 (p-doc (getf (getf p :documentation) :summary))
                 (doc-str (if p-doc (escape-lisp-string p-doc) "")))
            (format stream "(cl:define-symbol-macro ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf p :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))
        
        ;; Instance Properties
        (dolist (p instance-props)
          (let* ((pname (map-member-name (getf p :name)))
                 (readable (getf p :readable))
                 (writeable (getf p :writeable))
                 (get-method (getf p :get-method))
                 (set-method (getf p :set-method))
                 (p-doc (getf (getf p :documentation) :summary))
                 (doc-str (if p-doc (escape-lisp-string p-doc) "")))
            (when readable
              (format stream "(cl:defun ~A (obj)~%" pname)
              (when (> (length doc-str) 0)
                (format stream "  \"~A\"~%" doc-str))
              (format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\"))~%~%" fq-name get-method))
            (when writeable
              (if readable
                  (progn
                    (when is-value-type-p
                      (format stream ";; Note: Modifying a property of a value type (struct) via setf may only mutate~%")
                      (format stream ";; a boxed copy, leaving the original unchanged. Use caution with structs.~%"))
                    (format stream "(cl:defun (cl:setf ~A) (new-value obj)~%" pname)
                    (when (> (length doc-str) 0)
                      (format stream "  \"~A\"~%" doc-str))
                    (format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\" new-value))~%~%" fq-name set-method))
                  (progn
                    (when is-value-type-p
                      (format stream ";; Note: Modifying a property of a value type (struct) via setf may only mutate~%")
                      (format stream ";; a boxed copy, leaving the original unchanged. Use caution with structs.~%"))
                    (format stream "(cl:defun set-~A (obj new-value)~%" pname)
                    (when (> (length doc-str) 0)
                      (format stream "  \"~A\"~%" doc-str))
                    (format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\" new-value))~%~%" fq-name set-method))))))
        
        ;; Methods - Generated from method groups with overload handling
        (dolist (group method-groups)
          (let* ((name (car group))
                 (group-methods (cdr group))
                 (static-p (getf (first group-methods) :is-static))
                 (clean-methods (remove-if-not #'clean-method-p group-methods))
                 (dirty-methods (remove-if-not #'dirty-method-p group-methods))
                 (clean-count (length clean-methods))
                 (dirty-count (length dirty-methods))
                 (kebab-name (map-member-name name)))
            
            (cond
              ;; Case 1: No clean overloads - all are dirty (ref/out/params/defaults)
              ((= clean-count 0)
               (format stream ";; The following C# ~A.~A overloads have special parameter types~%" fq-name name)
               (format stream ";; (ref, out, params, or defaults) and are not yet supported:~%")
               (dolist (dm dirty-methods)
                 (format stream ";;   ~A~%" (method-signature-str dm)))
               (format stream "~%"))
              
              ;; Case 2: Single clean overload
              ((= clean-count 1)
               (let* ((m (first clean-methods))
                      (mname kebab-name)
                      (m-doc (getf m :documentation))
                      (summary (getf m-doc :summary))
                      (returns (getf m-doc :returns))
                      (params (getf m :parameters))
                      (is-generic-p (getf m :is-generic))
                      (param-names (mapcar (lambda (p) (map-param-name (getf p :name))) params))
                      (args-str (cond
                                  ((and static-p is-generic-p)
                                   (format nil "type~@[ ~{~A~^ ~}~]" param-names))
                                  (static-p
                                   (format nil "~{~A~^ ~}" param-names))
                                  (is-generic-p
                                   (format nil "type obj~@[ ~{~A~^ ~}~]" param-names))
                                  (t
                                   (format nil "obj~@[ ~{~A~^ ~}~]" param-names))))
                      (docstring (build-docstring summary returns params m-doc))
                      (escaped-docstring (escape-lisp-string docstring))
                      (dotnet-method-name (or (getf m :mangled-name) name))
                      ;; For static method params, add (the (dotnet "Type") arg) hints
                      (static-typed-args
                        (if static-p
                            (mapcar (lambda (pn pt)
                                      (format nil "(cl:the (dotnet \"~A\") ~A)" pt pn))
                                    param-names
                                    (mapcar (lambda (p) (getf p :type)) params))
                            nil)))
                 
                 (format stream "(cl:defun ~A (~A)~%" mname args-str)
                 (when (> (length escaped-docstring) 0)
                   (format stream "  \"~A\"~%" escaped-docstring))
                 (cl:cond
                   ((and static-p is-generic-p)
                    (format stream "  (dotnet:static-generic <type-str> \"~A\" (cl:list type)~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names))
                   (static-p
                    (if static-typed-args
                        (format stream "  (dotnet:static <type-str> \"~A\"~@[~{ ~A~}~]))~%~%" dotnet-method-name static-typed-args)
                        (format stream "  (dotnet:static <type-str> \"~A\"~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names)))
                   (is-generic-p
                    (format stream "  (dotnet:invoke-generic (cl:the (dotnet \"~A\") obj) \"~A\" (cl:list type)~@[ ~{~A~^ ~}~]))~%~%" fq-name dotnet-method-name param-names))
                   (cl:t
                    (format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\"~@[ ~{~A~^ ~}~]))~%~%" fq-name dotnet-method-name param-names)))
                 ;; Emit dirty overload doc-comment if any
                 (when (> dirty-count 0)
                   (format stream ";; Note: ~A.~A also has the following overloads with special~%" fq-name name)
                   (format stream ";; parameter types (ref, out, params, or defaults) that are not~%")
                   (format stream ";; yet supported:~%")
                   (dolist (dm dirty-methods)
                     (format stream ";;   ~A~%" (method-signature-str dm)))
                   (format stream "~%"))))
              
              ;; Case 3: Multiple clean overloads (2 or more)
              (t
               ;; Generate passthrough &rest function for DotCL runtime dispatch
               (let* ((first-clean (first clean-methods))
                      (is-generic-p (getf first-clean :is-generic))
                      (is-operator (uiop:string-prefix-p "op_" (or (getf first-clean :mangled-name) "")))
                      (passthrough-args (cl:cond
                                          ((and static-p is-generic-p) "type cl:&rest args")
                                          (static-p "cl:&rest args")
                                          (is-generic-p "type obj cl:&rest args")
                                          (cl:t "obj cl:&rest args"))))
                 (format stream "(cl:defun ~A (~A)~%" kebab-name passthrough-args)
                 (format stream "  \"Passthrough for ~A.~A overloads. Dispatches at runtime.\"~%" fq-name name)
                 (cl:cond
                   (is-operator
                    (format stream "  (cl:cond~%")
                    (dolist (cm clean-methods)
                      (let ((test-str (format-overload-test cm))
                            (overload-fn (method-overload-name cm)))
                        (format stream "    (~A~%     (cl:apply (cl:function ~A) args))~%" test-str overload-fn)))
                    (format stream "    (cl:t (cl:error \"~A.~A: no matching overload found for args: ~~S\" args))))~%~%" fq-name name))
                   ((and static-p is-generic-p)
                    (format stream "  (cl:apply (cl:function dotnet:static-generic) <type-str> \"~A\" (cl:list type) args))~%~%" name))
                   (static-p
                    (format stream "  (cl:apply (cl:function dotnet:static) <type-str> \"~A\" args))~%~%" name))
                   (is-generic-p
                    (format stream "  (cl:apply (cl:function dotnet:invoke-generic) (cl:the (dotnet \"~A\") obj) \"~A\" (cl:list type) args))~%~%" fq-name name))
                   (cl:t
                    (format stream "  (cl:apply (cl:function dotnet:invoke) (cl:the (dotnet \"~A\") obj) \"~A\" args))~%~%" fq-name name)))
                 ;; Generate per-overload typed functions with type-suffixed names
                 (dolist (cm clean-methods)
                   (let* ((mname (method-overload-name cm))
                          (m-doc (getf cm :documentation))
                          (summary (getf m-doc :summary))
                          (returns (getf m-doc :returns))
                          (params (getf cm :parameters))
                          (is-generic-overload-p (getf cm :is-generic))
                          (is-static-overload-p (getf cm :is-static))
                          (param-names (mapcar (lambda (p) (map-param-name (getf p :name))) params))
                          (overload-signature (method-signature-str cm))
                          (args-str (cl:cond
                                      ((and is-static-overload-p is-generic-overload-p)
                                       (format nil "type~@[ ~{~A~^ ~}~]" param-names))
                                      (is-static-overload-p
                                       (format nil "~{~A~^ ~}" param-names))
                                      (is-generic-overload-p
                                       (format nil "type obj~@[ ~{~A~^ ~}~]" param-names))
                                      (cl:t
                                       (format nil "obj~@[ ~{~A~^ ~}~]" param-names))))
                          (docstring (build-docstring summary returns params m-doc))
                          (escaped-docstring (escape-lisp-string docstring))
                          ;; Construct a note about the specific overload signature
                          (overload-note (format nil "Calls ~A.~A ~A" fq-name name overload-signature))
                          (full-docstring (if (> (length docstring) 0)
                                              (concatenate 'string overload-note ". " docstring)
                                              overload-note))
                          (escaped-full-doc (escape-lisp-string full-docstring))
                          (dotnet-method-name (or (getf cm :mangled-name) name))
                          ;; Static method type hints for typed overloads
                          (static-typed-args
                            (if is-static-overload-p
                                (mapcar (lambda (pn pt)
                                          (format nil "(cl:the (dotnet \"~A\") ~A)" pt pn))
                                        param-names
                                        (mapcar (lambda (p) (getf p :type)) params))
                                nil)))
                     (format stream "(cl:defun ~A (~A)~%" mname args-str)
                     (format stream "  \"~A\"~%" escaped-full-doc)
                     (cl:cond
                       ((and is-static-overload-p is-generic-overload-p)
                        (format stream "  (dotnet:static-generic <type-str> \"~A\" (cl:list type)~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names))
                       (is-static-overload-p
                        (if static-typed-args
                            (format stream "  (dotnet:static <type-str> \"~A\"~@[~{ ~A~}~]))~%~%" dotnet-method-name static-typed-args)
                            (format stream "  (dotnet:static <type-str> \"~A\"~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names)))
                       (is-generic-overload-p
                        (format stream "  (dotnet:invoke-generic (cl:the (dotnet \"~A\") obj) \"~A\" (cl:list type)~@[ ~{~A~^ ~}~]))~%~%" fq-name dotnet-method-name param-names))
                       (cl:t
                        (format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\"~@[ ~{~A~^ ~}~]))~%~%" fq-name dotnet-method-name param-names))))))
                 ;; Emit dirty overload doc-comment if any
                 (when (> dirty-count 0)
                   (format stream ";; Note: ~A.~A also has the following overloads with special~%" fq-name name)
                   (format stream ";; parameter types (ref, out, params, or defaults) that are not~%")
                   (format stream ";; yet supported:~%")
                   (dolist (dm dirty-methods)
                     (format stream ";;   ~A~%" (method-signature-str dm)))
                   (format stream "~%"))))))
        ) ;; close with-open-file
      ) ;; close inner analysis let*
    ) ;; close outer let*
  ) ;; close defun generate-class-file

(defun generate-assembly-packages (metadata-file class-filter output-dir &optional constant-properties-list)
  "Loads the metadata-file, filters classes by class-filter, and generates output Lisp files."
  (unless (probe-file metadata-file)
    (error "Metadata file not found: ~A" metadata-file))
  
  (let* ((metadata (utils:safe-read-form-from-file metadata-file))
         (filters (and class-filter (> (length class-filter) 0) (split-string class-filter #\;)))
         (classes-to-gen (if filters
                             (remove-if-not
                              (lambda (c)
                                (member (getf c :fully-qualified-name) filters :test #'string=))
                              metadata)
                             metadata)))
    
    (when (and filters (= 0 (length classes-to-gen)))
      (utils:format-red *error-output* "Warning: No classes matched the filter ~S~%" class-filter))
    
    (dolist (cls classes-to-gen)
      (format *error-output* "Generating package for C# Class: ~A~%" (getf cls :fully-qualified-name))
      (generate-class-file cls output-dir constant-properties-list))
    
    t))

(defun run-assembly-package-generator (metadata-file class-filter output-dir &optional constant-properties-str)
  "CLI entry point called by DotclHost.Call. Maps string parameters safely."
  (handler-case
      (let ((mfile (and metadata-file (> (length metadata-file) 0) metadata-file))
            (cfilter (and class-filter (> (length class-filter) 0) class-filter))
            (odir (and output-dir (> (length output-dir) 0) output-dir))
            (cprops (and constant-properties-str (> (length constant-properties-str) 0) (split-string constant-properties-str #\,))))
        (unless mfile
          (error "Metadata file path is required."))
        (unless odir
          (error "Output directory path is required."))
        (generate-assembly-packages mfile cfilter odir cprops))
    (error (c)
      (utils:format-red *error-output* "Error in assembly-package-generator: ~A~%" c)
      (error c))))
