;;; Douglas P. Fields, Jr. - symbolics@lisp.engineer
;;;
;;; Developed with Antigravity CLI (Gemini 3.5 Flash)
;;;
;;; Assembly Package Generator
;;;
;;; This module parses metadata generated by AssemblyToLispy and produces
;;; Common Lisp source files mapping C# classes to Lisp packages.
;;;
;;; It supports Phase 1 functionality: basic package infrastructure and
;;; simplest member translation (non-overloaded, non-generic members).

(in-package :assembly-package-generator)

(defparameter *generator-version* 6
  "Integer version number for the generated Lisp source files.")

(defun camel-to-kebab (name)
  "Convert a PascalCase/camelCase string to Lisp kebab-case.
   Also maps dot characters '.' to hyphens '-'."
  (let ((len (length name)))
    (with-output-to-string (sb)
      (loop for i from 0 to (1- len)
            for c = (char name i)
            do (cond
                 ((char= c #\.)
                  (write-char #\- sb))
                 ((upper-case-p c)
                  (when (and (> i 0)
                             (char/= (char name (1- i)) #\-)
                             (char/= (char name (1- i)) #\.)
                             (or (not (upper-case-p (char name (1- i))))
                                 (and (< (1+ i) len)
                                      (lower-case-p (char name (1+ i))))))
                    (write-char #\- sb))
                  (write-char (char-downcase c) sb))
                 (t
                  (write-char c sb)))))))

(defun split-string (string &optional (separator #\;))
  "Split a string into a list of substrings at occurrences of the separator character."
  (let ((result nil)
        (start 0)
        (len (length string)))
    (loop for i from 0 to (1- len)
          do (when (char= (char string i) separator)
               (push (subseq string start i) result)
               (setf start (1+ i))))
    (when (<= start len)
      (push (subseq string start len) result))
    (nreverse result)))

(defun map-param-name (name)
  "Convert a C# parameter name to a safe Lisp parameter name,
   renaming reserved words where necessary."
  (let ((kebab (camel-to-kebab name)))
    (cond
      ((string= kebab "t") "t-val")
      ((string= kebab "nil") "nil-val")
      (t kebab))))

(defun escape-lisp-string (str)
  "Escapes double quotes and backslashes in a string for safe output within Lisp strings."
  (with-output-to-string (out)
    (loop for c across str
          do (cond
               ((char= c #\") (write-string "\\\"" out))
               ((char= c #\\) (write-string "\\\\" out))
               (t (write-char c out))))))

(defun get-iso-8601-time ()
  "Get the current UTC time formatted as an ISO 8601 string."
  (multiple-value-bind (second minute hour date month year day-of-week daylight-saving-p time-zone)
      (decode-universal-time (get-universal-time) 0)
    (declare (ignore day-of-week daylight-saving-p time-zone))
    (format nil "~4,'0D-~2,'0D-~2,'0DT~2,'0D:~2,'0D:~2,'0DZ"
            year month date hour minute second)))

(defun literal-field-p (field)
  "Checks if a field plist defines a static literal/constant field."
  (and (getf field :static)
       (getf field :literal)))

(defun runtime-readonly-field-p (field)
  "Checks if a field plist defines a static init-only field that is not literal."
  (and (getf field :static)
       (getf field :init-only)
       (not (getf field :literal))))

(defun constant-property-p (prop)
  "Checks if a property plist defines a static read-only property."
  (and (getf prop :static)
       (getf prop :readable)
       (not (getf prop :writeable))))

(defun generic-type-p (type-str)
  "Checks if a C# type signature string represents a generic type (contains a backtick or exclamation point)."
  (and type-str (or (find #\` type-str) (find #\! type-str))))

(defun simple-method-p (method all-methods)
  "Returns t if the method qualifies for Phase 1 compilation.
   Criteria:
   - No overloads (exactly one method signature with this name in the class).
   - No generic parameters/return type.
   - No default parameter values.
   - No special parameter modifiers (ref, out, ref-readonly, params).
   - No operator overloads.
   - No property accessors (get_/set_)."
  (let* ((name (getf method :name))
         (params (getf method :parameters))
         (static-p (getf method :is-static)))
    (declare (ignore static-p))
    (and name
         ;; Exclude operators and property accessors
         (not (uiop:string-prefix-p "op_" name))
         (not (uiop:string-prefix-p "get_" name))
         (not (uiop:string-prefix-p "set_" name))
         ;; Check for no overloads in the class
         (= 1 (count name all-methods :key (lambda (m) (getf m :name)) :test #'string=))
         ;; Check return type for generic markers
         (not (generic-type-p (getf method :return-type)))
         ;; Check all parameters
         (every (lambda (p)
                  (and (not (getf p :has-default))
                       (not (getf p :out))
                       (not (getf p :ref))
                       (not (getf p :ref-readonly))
                       (not (getf p :params))
                       (not (generic-type-p (getf p :type)))))
                params))))

(defun build-docstring (summary returns parameters doc-plist)
  "Builds a formatted docstring from documentation elements."
  (with-output-to-string (out)
    (when (and summary (> (length summary) 0))
      (format out "Summary: ~A~%" summary))
    (when (and returns (> (length returns) 0))
      (format out "Returns: ~A~%" returns))
    (when (and parameters doc-plist)
      (let ((doc-params (getf doc-plist :parameters)))
        (format out "Parameters:~%")
        (dolist (p parameters)
          (let* ((pname (getf p :name))
                 (ptype (getf p :type))
                 (pdoc (find pname doc-params :key (lambda (dp) (getf dp :name)) :test #'string=))
                 (pdesc (if pdoc (getf pdoc :description) "")))
            (format out "  - ~A (~A): ~A~%"
                    (map-param-name pname)
                    ptype
                    pdesc)))))))

(defun generate-class-file (class-plist output-dir &optional constant-properties-list)
  "Generates the Lisp source file for a single class plist."
  (let* ((fq-name (getf class-plist :fully-qualified-name))
         (pkg-name (camel-to-kebab fq-name))
         (output-file (merge-pathnames (make-pathname :name pkg-name :type "lisp")
                                       (pathname (concatenate 'string output-dir "/"))))
         (fields (getf class-plist :fields))
         (properties (getf class-plist :properties))
         (methods (getf class-plist :methods))
         (creation-time (get-iso-8601-time)))
    
    (ensure-directories-exist output-file :verbose t)
    
    ;; 1. Analyze and extract valid Phase 1 members
    (let* ((literal-fields (remove-if-not #'literal-field-p fields))
           (runtime-fields-all (remove-if-not #'runtime-readonly-field-p fields))
           (pure-const-fields (remove-if-not (lambda (f) (or (member "*" constant-properties-list :test #'string=) (member (getf f :name) constant-properties-list :test #'string-equal))) runtime-fields-all))
           (dynamic-const-fields (remove-if (lambda (f) (or (member "*" constant-properties-list :test #'string=) (member (getf f :name) constant-properties-list :test #'string-equal))) runtime-fields-all))
           (const-props (remove-if-not #'constant-property-p properties))
           (pure-const-props (remove-if-not (lambda (p) (or (member "*" constant-properties-list :test #'string=) (member (getf p :name) constant-properties-list :test #'string-equal))) const-props))
           (dynamic-const-props (remove-if (lambda (p) (or (member "*" constant-properties-list :test #'string=) (member (getf p :name) constant-properties-list :test #'string-equal))) const-props))
           (simple-methods (remove-if-not (lambda (m) (simple-method-p m methods)) methods))
           (exports nil)
           (shadows nil))
      
      ;; Collect all exports
      (push "<type>" exports)
      (push "<type-str>" exports)
      (push "<creation>" exports)
      (push "<version>" exports)
      
      (dolist (f literal-fields)
        (push (format nil "+~A+" (camel-to-kebab (getf f :name))) exports))
      (dolist (f pure-const-fields)
        (push (format nil "+~A+" (camel-to-kebab (getf f :name))) exports))
      (dolist (f dynamic-const-fields)
        (push (camel-to-kebab (getf f :name)) exports))
      (dolist (p pure-const-props)
        (push (format nil "+~A+" (camel-to-kebab (getf p :name))) exports))
      (dolist (p dynamic-const-props)
        (push (camel-to-kebab (getf p :name)) exports))
      (dolist (m simple-methods)
        (push (camel-to-kebab (getf m :name)) exports))
      
      (setf exports (nreverse exports))
      
      ;; Identify exported symbols that conflict with CL and must be shadowed
      (dolist (exp exports)
        (multiple-value-bind (sym status) (find-symbol (string-upcase exp) :common-lisp)
          (when (and sym (eq status :external))
            (push exp shadows))))
      (setf shadows (nreverse shadows))
      
      ;; 2. Write to the Lisp output file
      (with-open-file (stream output-file :direction :output :if-exists :supersede :if-does-not-exist :create)
        ;; Comments
        (format stream ";;; Generated automatically. Do not edit.~%")
        (format stream ";;; Class: ~A~%" fq-name)
        (format stream ";;; Generator Version: ~D~%" *generator-version*)
        (format stream ";;; Creation Date: ~A~%~%" creation-time)
        
        ;; Preamble
        (format stream "(in-package :cl-user)~%~%")
        (format stream "(defpackage :~A~%" pkg-name)
        (format stream "  (:use :cl)~%")
        (when shadows
          (format stream "  (:shadow~%")
          (dolist (shad shadows)
            (format stream "   #:~A~%" shad))
          (format stream "  )~%"))
        (format stream "  (:export~%")
        (dolist (exp exports)
          (format stream "   #:~A~%" exp))
        (format stream "  ))~%~%")
        
        (format stream "(in-package :~A)~%~%" pkg-name)
        
        ;; Type Constants
        (format stream "(defconstant <type> (monoutils:get-type \"~A\"))~%" fq-name)
        (format stream "(defconstant <type-str> \"~A\")~%" fq-name)
        (format stream "(defconstant <creation> \"~A\")~%" creation-time)
        (format stream "(defconstant <version> ~D)~%~%" *generator-version*)
        
        ;; CLOS Type Registration
        (format stream ";; Register C# Type with CLOS~%")
        (format stream "(eval-when (:compile-toplevel :load-toplevel :execute)~%")
        (format stream "  (dotnet:static \"DotCL.Runtime\" \"EnsureDotNetTypeClass\"~%")
        (format stream "                 (dotnet:resolve-type \"~A\")))~%~%" fq-name)
        
        ;; Compile-Time Constants (Literal Fields)
        (dolist (f literal-fields)
          (let* ((cname (format nil "+~A+" (camel-to-kebab (getf f :name))))
                 (f-doc (getf (getf f :documentation) :summary))
                 (doc-str (if f-doc (escape-lisp-string f-doc) "")))
            (format stream "(defconstant ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf f :name))
            (if (> (length doc-str) 0)
                (format stream "(setf (documentation '~A 'variable) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))
        
        ;; Runtime Read-Only Fields (Constants)
        (dolist (f pure-const-fields)
          (let* ((cname (format nil "+~A+" (camel-to-kebab (getf f :name))))
                 (f-doc (getf (getf f :documentation) :summary))
                 (doc-str (if f-doc (escape-lisp-string f-doc) "")))
            (format stream "(defconstant ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf f :name))
            (if (> (length doc-str) 0)
                (format stream "(setf (documentation '~A 'variable) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))

        ;; Runtime Read-Only Fields (Dynamic)
        (dolist (f dynamic-const-fields)
          (let* ((cname (camel-to-kebab (getf f :name)))
                 (f-doc (getf (getf f :documentation) :summary))
                 (doc-str (if f-doc (escape-lisp-string f-doc) "")))
            (format stream "(define-symbol-macro ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf f :name))
            (if (> (length doc-str) 0)
                (format stream "(setf (documentation '~A 'variable) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))
        
        ;; Runtime Read-Only Properties
        ;; Pure Constant Properties
        (dolist (p pure-const-props)
          (let* ((cname (format nil "+~A+" (camel-to-kebab (getf p :name))))
                 (p-doc (getf (getf p :documentation) :summary))
                 (doc-str (if p-doc (escape-lisp-string p-doc) "")))
            (format stream "(defconstant ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf p :name))
            (if (> (length doc-str) 0)
                (format stream "(setf (documentation '~A 'variable) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))

        ;; Runtime Read-Only Properties
        (dolist (p dynamic-const-props)
          (let* ((cname (camel-to-kebab (getf p :name)))
                 (p-doc (getf (getf p :documentation) :summary))
                 (doc-str (if p-doc (escape-lisp-string p-doc) "")))
            (format stream "(define-symbol-macro ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf p :name))
            (if (> (length doc-str) 0)
                (format stream "(setf (documentation '~A 'variable) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))
        
        ;; Methods
        (dolist (m simple-methods)
          (let* ((mname (camel-to-kebab (getf m :name)))
                 (static-p (getf m :is-static))
                 (m-doc (getf m :documentation))
                 (summary (getf m-doc :summary))
                 (returns (getf m-doc :returns))
                 (params (getf m :parameters))
                 (param-names (mapcar (lambda (p) (map-param-name (getf p :name))) params))
                 (args-str (if static-p
                               (format nil "~{~A~^ ~}" param-names)
                               (format nil "obj~@[ ~{~A~^ ~}~]" param-names)))
                 (docstring (build-docstring summary returns params m-doc))
                 (escaped-docstring (escape-lisp-string docstring)))
            
            ;; Retrieve the C# side method name. If a mangled-name exists (e.g. for operators),
            ;; it is used; otherwise the standard method name is used.
            (let ((dotnet-method-name (or (getf m :mangled-name) (getf m :name))))
              (format stream "(defun ~A (~A)~%" mname args-str)
              (when (> (length escaped-docstring) 0)
                (format stream "  \"~A\"~%" escaped-docstring))
              (if static-p
                  (format stream "  (dotnet:static <type-str> \"~A\"~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names)
                  (format stream "  (dotnet:invoke obj \"~A\"~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names)))))))))

(defun generate-assembly-packages (metadata-file class-filter output-dir &optional constant-properties-list)
  "Loads the metadata-file, filters classes by class-filter, and generates output Lisp files."
  (unless (probe-file metadata-file)
    (error "Metadata file not found: ~A" metadata-file))
  
  (let* ((metadata (utils:safe-read-form-from-file metadata-file))
         (filters (and class-filter (> (length class-filter) 0) (split-string class-filter #\;)))
         (classes-to-gen (if filters
                             (remove-if-not
                              (lambda (c)
                                (member (getf c :fully-qualified-name) filters :test #'string=))
                              metadata)
                             metadata)))
    
    (when (and filters (= 0 (length classes-to-gen)))
      (format *error-output* "Warning: No classes matched the filter ~S~%" class-filter))
    
    (dolist (cls classes-to-gen)
      (format *error-output* "Generating package for C# Class: ~A~%" (getf cls :fully-qualified-name))
      (generate-class-file cls output-dir constant-properties-list))
    
    t))

(defun run-assembly-package-generator (metadata-file class-filter output-dir &optional constant-properties-str)
  "CLI entry point called by DotclHost.Call. Maps string parameters safely."
  (let ((mfile (and metadata-file (> (length metadata-file) 0) metadata-file))
        (cfilter (and class-filter (> (length class-filter) 0) class-filter))
        (odir (and output-dir (> (length output-dir) 0) output-dir))
        (cprops (and constant-properties-str (> (length constant-properties-str) 0) (split-string constant-properties-str #\,))))
    (unless mfile
      (error "Metadata file path is required."))
    (unless odir
      (error "Output directory path is required."))
    (generate-assembly-packages mfile cfilter odir cprops)))
