;;; Douglas P. Fields, Jr. - symbolics@lisp.engineer
;;;
;;; Integration tests for generated C# Lisp packages (cspackages/).
;;;
;;; Tests verify that methods, properties, constants, and operator overloads
;;; generated by assembly-package-generator version 10+ work correctly.
;;; Tests are run when this file is loaded.

(in-package :dungeon-slime-tests)

(defun run-cspackages-tests ()
  "Run all integration tests for generated C# packages."

  (format *error-output* "--- Running C# Packages Integration Tests ---~%")

  ;; Compare two values for equality, treating numbers by value
  ;; rather than by type+value (since DotCL may return double-float
  ;; for what C# defines as single-float).
  (defun %cspkg-equal (a b)
    (if (and (numberp a) (numberp b))
        (= a b)
        (equal a b)))

  ;; Helper assertion macro
  (defmacro assert-cspkg (form expected-value description)
    `(let ((result ,form))
      (if (%cspkg-equal result ,expected-value)
          (format *error-output* "[cspackages-test] PASS ~A: ~S -> ~S~%"
                  ,description result result)
          (progn
            (utils:format-red *error-output*
              "[cspackages-test] FAIL ~A: Expected ~S but got ~S~%"
              ,description ,expected-value result)
            (error "Test failure: ~A" ,description)))))

  ;; Helper for error signaling tests
  (defmacro assert-cspkg-error (form description)
    `(handler-case
      (progn
        ,form
        (utils:format-red *error-output*
          "[cspackages-test] FAIL ~A: No error signaled~%" ,description)
        (error "Test failure: ~A" ,description))
      (error (e)
        (format *error-output* "[cspackages-test] PASS ~A: signalled ~A~%"
                ,description (type-of e)))))

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; 1. Vector2 Method Tests
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

  (format *error-output* "--- Vector2 Method Tests ---~%")

  (let* ((v1 (v2:new 3.0e0 4.0e0))
         (v2 (v2:new 0.0e0 0.0e0))
         (v3 (v2:new 1.0e0 0.0e0))
         (v4 (v2:new 0.0e0 1.0e0))
         (v2-pkg1 :microsoft-xna-framework-vector2))

    ;; Vector2.DistanceSquared - static, single clean + single dirty overload
    (assert-cspkg (funcall (find-symbol "DISTANCE-SQUARED" v2-pkg1) v1 v2) 25.0e0
                  "Vector2.DistanceSquared (3,4)->(0,0) = 25")

    (assert-cspkg (funcall (find-symbol "DISTANCE-SQUARED" v2-pkg1) v1 v1) 0.0e0
                  "Vector2.DistanceSquared same point = 0")

    ;; Vector2.Reflect - static, single clean overload
    (let* ((reflect (find-symbol "REFLECT" v2-pkg1))
           (v2-eq (find-symbol "=" v2-pkg1))
           (r (funcall reflect (v2:new 1.0e0 -1.0e0) (v2:new 0.0e0 1.0e0))))
      (assert-cspkg (funcall v2-eq r (v2:new 1.0e0 1.0e0)) t
                    "Vector2.Reflect (1,-1) about (0,1) = (1,1)"))

    (let* ((reflect (find-symbol "REFLECT" v2-pkg1))
           (v2-eq (find-symbol "=" v2-pkg1))
           (r (funcall reflect (v2:new 1.0e0 1.0e0) (v2:new 1.0e0 0.0e0))))
      (assert-cspkg (funcall v2-eq r (v2:new -1.0e0 1.0e0)) t
                    "Vector2.Reflect (1,1) about (1,0) = (-1,1)"))

    ;; Vector2.Length - instance property (version 9)
    (assert-cspkg (funcall (find-symbol "LENGTH" v2-pkg1) v1) 5.0e0
                  "Vector2.Length of (3,4) = 5")

    ;; Vector2.LengthSquared - instance method (version 9)
    (assert-cspkg (funcall (find-symbol "LENGTH-SQUARED" v2-pkg1) v1) 25.0e0
                  "Vector2.LengthSquared of (3,4) = 25")

    ;; Vector2 instance operators via cspackage (version 9)
    (let* ((v2-eq (find-symbol "=" v2-pkg1))
           (v2-add (find-symbol "+" v2-pkg1)))
      (assert-cspkg
        (funcall v2-eq (funcall v2-add v3 v4) (v2:new 1.0e0 1.0e0)) t
        "Vector2 + operator (UnitX + UnitY = One)"))

    ;; Bad type argument should signal an error
    (assert-cspkg-error
      (funcall (find-symbol "DISTANCE-SQUARED" v2-pkg1) "not-a-vector" v2)
      "Vector2.DistanceSquared errors on bad type arg")

    (assert-cspkg-error
      (funcall (find-symbol "REFLECT" v2-pkg1) "not-a-vector" v3)
      "Vector2.Reflect errors on bad type arg")
    )

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; 2. Rectangle Method Tests
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

  (format *error-output* "--- Rectangle Method Tests ---~%")

  (let* ((r-outer (rect:new 0 0 100 100))
         (r-inner (rect:new 10 10 20 20))
         (v-point (v2:new 50.0e0 50.0e0))
         (rect-pkg :microsoft-xna-framework-rectangle))

    ;; Rectangle.Intersects - single clean overload + dirty
    (let ((intersects (find-symbol "INTERSECTS" rect-pkg)))
      (assert-cspkg (funcall intersects r-outer r-inner) t
                    "Rectangle.Intersects overlapping rectangles")
      (assert-cspkg (funcall intersects (rect:new 0 0 32 32) (rect:new 100 100 32 32)) nil
                    "Rectangle.Intersects non-overlapping rectangles"))

    ;; Rectangle.Contains - multi-overload (5 clean + 3 dirty)
    ;; Passthrough dispatch
    (let ((contains (find-symbol "CONTAINS" rect-pkg)))
      (assert-cspkg (funcall contains r-outer v-point) t
                    "Rectangle.Contains passthrough center point")
      (assert-cspkg (funcall contains r-outer (v2:new 200 200)) nil
                    "Rectangle.Contains passthrough outside point")
      (assert-cspkg (funcall contains r-outer r-inner) t
                    "Rectangle.Contains passthrough contained rectangle")
      (assert-cspkg (funcall contains r-inner r-outer) nil
                    "Rectangle.Contains passthrough larger rectangle"))

    ;; Typed overload versions
    (let ((contains-vector2 (find-symbol "CONTAINS-VECTOR2" rect-pkg))
          (contains-rectangle (find-symbol "CONTAINS-RECTANGLE" rect-pkg)))
      (assert-cspkg (funcall contains-vector2 r-outer v-point) t
                    "Rectangle.Contains Vector2 typed overload")
      (assert-cspkg (funcall contains-vector2 r-outer (v2:new 200 200)) nil
                    "Rectangle.Contains Vector2 typed overload outside")
      (assert-cspkg (funcall contains-rectangle r-outer r-inner) t
                    "Rectangle.Contains Rectangle typed overload contained")
      (assert-cspkg (funcall contains-rectangle r-inner r-outer) nil
                    "Rectangle.Contains Rectangle typed overload larger"))

    ;; Rectangle property accessors (version 9)
    (assert-cspkg (funcall (find-symbol "LEFT" rect-pkg) r-outer) 0
                  "Rectangle.Left of (0,0,100,100) = 0")
    (assert-cspkg (funcall (find-symbol "RIGHT" rect-pkg) r-outer) 100
                  "Rectangle.Right of (0,0,100,100) = 100")
    (assert-cspkg (funcall (find-symbol "TOP" rect-pkg) r-outer) 0
                  "Rectangle.Top of (0,0,100,100) = 0")
    (assert-cspkg (funcall (find-symbol "BOTTOM" rect-pkg) r-outer) 100
                  "Rectangle.Bottom of (0,0,100,100) = 100")

    ;; Bad type argument to passthrough should signal an error
    (assert-cspkg-error
      (funcall (find-symbol "CONTAINS" rect-pkg) r-outer "not-a-vector")
      "Rectangle.Contains passthrough errors on bad type")

    ;; Bad type argument to typed overload should signal an error
    (assert-cspkg-error
      (funcall (find-symbol "CONTAINS-RECTANGLE" rect-pkg) r-outer "bad-arg")
      "Rectangle.Contains Rectangle typed overload errors on bad arg")
    )

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; 3. Point Method Tests
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

  (format *error-output* "--- Point Method Tests ---~%")

  (let* ((zero (dotnet:static "Microsoft.Xna.Framework.Point" "Zero"))
         (one (dotnet:new "Microsoft.Xna.Framework.Point" 1 1))
         (point-pkg :microsoft-xna-framework-point))

    ;; Point.ToVector2 - instance method
    (let ((v (funcall (find-symbol "TO-VECTOR2" point-pkg) one))
          (v2-eq (find-symbol "=" :microsoft-xna-framework-vector2)))
      (assert-cspkg (funcall v2-eq v (v2:new 1.0e0 1.0e0)) t
                    "Point.ToVector2 (1,1) = Vector2(1,1)"))

    ;; Point operators
    (let ((pt-eq (find-symbol "=" point-pkg))
          (pt-noteq (find-symbol "NOT=" point-pkg))
          (pt-add (find-symbol "+" point-pkg)))
      (assert-cspkg (funcall pt-eq zero zero) t
                    "Point = operator (true case)")
      (assert-cspkg (funcall pt-eq zero one) nil
                    "Point = operator (false case)")
      (assert-cspkg (funcall pt-noteq zero one) t
                    "Point not= operator (true case)")
      (let ((sum (funcall pt-add one one)))
        (assert-cspkg
          (funcall pt-eq sum (dotnet:new "Microsoft.Xna.Framework.Point" 2 2)) t
          "Point + operator (1,1)+(1,1) = (2,2)")))
    )

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; 4. TimeSpan Method Tests
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

  (format *error-output* "--- TimeSpan Method Tests ---~%")

  (let* ((t1 (ts:from-ticks 100))
         (t2 (ts:from-ticks 200))
         (t3 (ts:from-ticks 100)))

    ;; TimeSpan operators (version 9)
    (assert-cspkg (ts:= t1 t3) t
                  "TimeSpan = operator (true case)")
    (assert-cspkg (ts:= t1 t2) nil
                  "TimeSpan = operator (false case)")
    (assert-cspkg (ts:not= t1 t2) t
                  "TimeSpan not= operator (true case)")
    (assert-cspkg (ts:< t1 t2) t
                  "TimeSpan < operator (true case)")
    (assert-cspkg (ts:> t2 t1) t
                  "TimeSpan > operator (true case)"))

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; 5. Edge Cases
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

  (format *error-output* "--- Edge Case Tests ---~%")

  (let* ((r (rect:new 0 0 100 100))
         (rect-pkg :microsoft-xna-framework-rectangle))

    ;; Rectangle.Contains with Point (no typed overload, uses passthrough)
    (let ((p (dotnet:new "Microsoft.Xna.Framework.Point" 50 50)))
      (assert-cspkg (funcall (find-symbol "CONTAINS" rect-pkg) r p) t
                    "Rectangle.Contains Point (through passthrough)"))

    ;; Rectangle.Contains(int, int) and Contains(float, float) passthrough
    (assert-cspkg (funcall (find-symbol "CONTAINS" rect-pkg) r 50 50) t
                  "Rectangle.Contains(int,int) passthrough center")
    (assert-cspkg (funcall (find-symbol "CONTAINS" rect-pkg) r 200 200) nil
                  "Rectangle.Contains(int,int) passthrough outside"))

  ;; Vector2 constant properties (version 9)
  (let* ((v2-pkg :microsoft-xna-framework-vector2)
         (v2-eq (find-symbol "=" v2-pkg)))
    (assert-cspkg (funcall v2-eq (symbol-value (find-symbol "+ZERO+" v2-pkg))
                           (v2:new 0.0e0 0.0e0)) t
                  "Vector2.Zero constant")
    (assert-cspkg (funcall v2-eq (symbol-value (find-symbol "+ONE+" v2-pkg))
                           (v2:new 1.0e0 1.0e0)) t
                  "Vector2.One constant")
    (assert-cspkg (funcall v2-eq (symbol-value (find-symbol "+UNIT-X+" v2-pkg))
                           (v2:new 1.0e0 0.0e0)) t
                  "Vector2.UnitX constant")
    (assert-cspkg (funcall v2-eq (symbol-value (find-symbol "+UNIT-Y+" v2-pkg))
                           (v2:new 0.0e0 1.0e0)) t
                  "Vector2.UnitY constant"))

  ;; Rectangle constant property (version 9)
  (let* ((rect-pkg :microsoft-xna-framework-rectangle)
         (empty (symbol-value (find-symbol "+EMPTY+" rect-pkg))))
    (assert-cspkg (and (= (funcall (find-symbol "LEFT" rect-pkg) empty) 0)
                       (= (funcall (find-symbol "TOP" rect-pkg) empty) 0)
                       (= (funcall (find-symbol "RIGHT" rect-pkg) empty) 0)
                       (= (funcall (find-symbol "BOTTOM" rect-pkg) empty) 0))
                  t
                  "Rectangle.Empty constant"))

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; 6. Constructor Tests (Version 11)
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (format *error-output* "--- Constructor Tests ---~%")

  ;; Vector2 Constructors (Struct, multi-overload)
  (let* ((v2-pkg :microsoft-xna-framework-vector2)
         (v2-eq (find-symbol "=" v2-pkg))
         (new-fn (find-symbol "NEW" v2-pkg))
         (new-single-single (find-symbol "NEW-SINGLE-SINGLE" v2-pkg))
         ;; Test default parameterless constructor (injected for structs)
         (v-def (funcall new-fn))
         ;; Test parameterized constructor via runtime dispatch (new)
         (v-param (funcall new-fn 3.0e0 4.0e0))
         ;; Test parameterized constructor via typed overload
         (v-typed (funcall new-single-single 3.0e0 4.0e0)))

    (assert-cspkg (funcall v2-eq v-def (v2:new 0.0e0 0.0e0)) t
                  "Vector2 default constructor (injected)")
    (assert-cspkg (funcall v2-eq v-param (v2:new 3.0e0 4.0e0)) t
                  "Vector2 constructor via new")
    (assert-cspkg (funcall v2-eq v-typed (v2:new 3.0e0 4.0e0)) t
                  "Vector2 constructor via new-single-single"))

  ;; Rectangle Constructors (Struct, multi-overload)
  (let* ((rect-pkg :microsoft-xna-framework-rectangle)
         (new-fn (find-symbol "NEW" rect-pkg))
         (new-int-int-int-int (find-symbol "NEW-INT32-INT32-INT32-INT32" rect-pkg))
         ;; Test default parameterless constructor
         (r-def (funcall new-fn))
         ;; Test parameterized constructor
         (r-param (funcall new-fn 10 20 100 200))
         ;; Test typed constructor
         (r-typed (funcall new-int-int-int-int 10 20 100 200)))

    (assert-cspkg (= (funcall (find-symbol "LEFT" rect-pkg) r-def) 0) t
                  "Rectangle default constructor left")
    (assert-cspkg (= (funcall (find-symbol "LEFT" rect-pkg) r-param) 10) t
                  "Rectangle parameterized constructor left")
    (assert-cspkg (= (funcall (find-symbol "LEFT" rect-pkg) r-typed) 10) t
                  "Rectangle typed constructor left"))

  ;; TimeSpan Constructors (Struct, multi-overload)
  (let* ((t-def (ts:new))
         (t-param (ts:new 5000))
         (t-typed (ts:new-int64 5000)))

    (assert-cspkg (ts:= t-def (ts:from-ticks 0)) t
                  "TimeSpan default constructor")
    (assert-cspkg (ts:= t-param (ts:from-ticks 5000)) t
                  "TimeSpan parameterized constructor")
    (assert-cspkg (ts:= t-typed (ts:from-ticks 5000)) t
                  "TimeSpan typed constructor"))

  ;; Uri Constructors (Class, multi-overload)
  (let* ((uri-pkg :system-uri)
         (new-fn (find-symbol "NEW" uri-pkg))
         (new-str (find-symbol "NEW-STRING" uri-pkg))
         ;; Test single parameter string constructor via new (class)
         (u-param (funcall new-fn "http://localhost/"))
         ;; Test single parameter string constructor via typed overload
         (u-typed (funcall new-str "http://localhost/")))

    (assert-cspkg (dotnet:invoke u-param "ToString") "http://localhost/"
                  "Uri constructor via new")
    (assert-cspkg (dotnet:invoke u-typed "ToString") "http://localhost/"
                  "Uri constructor via new-string"))

  (format *error-output* "--- C# Packages Integration Tests Completed ---~%"))
